import { APP_NAME } from "@/constants/system";
import { routing } from "@/i18n/routing";
import ReactQueryProvider from "@/providers/query-client-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { AnimatedToastProvider } from "@/share/ui/animated-toast";
import dayjs from "dayjs";
import updateLocale from "dayjs/plugin/updateLocale";
import { Metadata, Viewport } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";

dayjs.extend(updateLocale);

export const metadata: Metadata = {
  title: {
    template: "%s | " + APP_NAME,
    default: APP_NAME,
  },
  description: `Generated by ${APP_NAME}`,
  applicationName: "Sale Management",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/coffee.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/coffee.svg",
    apple: "/icon-192.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Sale Management",
  },
  formatDetection: {
    telephone: false,
  },
};

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#c2410c",
};

export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
      >
        <NextIntlClientProvider>
          <ThemeProvider>
            <AnimatedToastProvider>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </AnimatedToastProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
